In [1]:
from sklearn import datasets
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.utils.testing import assert_true, assert_false
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn import linear_model

In [2]:
iris = datasets.load_iris()


In [3]:
# Prints the type/type object of iris
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [4]:
# prints the dictionary keys of iris data
print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [5]:
# prints the type/type object of given attributes
print(type(iris.data), type(iris.target))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [6]:
iris.data[1:3]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [8]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# prints the no of rows and columns in the dataset
print(iris.data.shape)

(150, 4)


In [10]:
# prints the target set of the data
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [11]:
# Load iris training dataset
X = iris.data[:,:4]

# Load iris target set
Y = iris.target

In [12]:
X[1:3]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [13]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
# Convert datasets' type into dataframe

df = pd.DataFrame(X, columns = iris.feature_names)
df['target'] = iris.target
df.target = df.target.apply(lambda x : iris.target_names[x])

In [15]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.3)

In [17]:
X_train.shape

(105, 4)

In [18]:
X_train[0:10]

array([[4.5, 2.3, 1.3, 0.3],
       [6.9, 3.1, 5.4, 2.1],
       [6. , 2.9, 4.5, 1.5],
       [6.7, 3. , 5. , 1.7],
       [5.7, 2.8, 4.5, 1.3],
       [6.5, 3. , 5.8, 2.2],
       [5. , 3.4, 1.6, 0.4],
       [6.3, 2.7, 4.9, 1.8],
       [5.7, 2.8, 4.1, 1.3],
       [6.4, 2.7, 5.3, 1.9]])

In [19]:
X_train[:,0]

array([4.5, 6.9, 6. , 6.7, 5.7, 6.5, 5. , 6.3, 5.7, 6.4, 5.1, 5.1, 5.9,
       4.8, 5. , 5.7, 6.2, 5.2, 6.3, 5.4, 6.7, 5.2, 5.1, 5.1, 6.4, 4.7,
       4.6, 5.1, 6.7, 6.7, 6.5, 7.7, 5.8, 7.7, 4.8, 4.9, 6.8, 6.1, 5.1,
       6. , 6.9, 6.2, 4.9, 4.9, 6.1, 5.6, 6.1, 6.7, 6.6, 5.7, 4.4, 4.4,
       7.6, 5.9, 5.8, 5.1, 6.4, 4.7, 5.4, 5.6, 4.9, 6.4, 5.9, 5.2, 7. ,
       5.7, 6.2, 6.5, 5.1, 7.4, 6.1, 6.8, 6.2, 6.3, 7.3, 5. , 5.8, 6. ,
       5. , 6.7, 6.1, 5.5, 5.5, 5. , 4.4, 6. , 6.3, 5.4, 5.7, 5.5, 5.7,
       4.6, 6.7, 6.3, 6.7, 6.3, 7.2, 4.8, 5. , 5.2, 6. , 5.6, 4.8, 6. ,
       5.3])

In [24]:
# scale our data
from sklearn.svm import SVC

from sklearn.neighbors import KNeighborsClassifier as Knn
scaler = MinMaxScaler()

X_trained_scale = scaler.fit_transform(X_train)

model = Knn(n_neighbors=5)
model.fit(X_trained_scale,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [25]:
X_test_scaled = scaler.transform(X_test)
y_pred = model.predict(X_test_scaled)

In [27]:
#y_pred_s = clf.predict(X_test_s)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9777777777777777


In [28]:
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

data = datasets.load_iris()
X = data.data[:,:4]
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

model = Knn(n_neighbors=5)
model.fit(X_train_scaled, y_train)

X_test_scaled = scaler.transform(X_test)
y_pred = model.predict(X_test_scaled)


In [29]:
#y_pred_s = clf.predict(X_test_s)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9777777777777777


In [30]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

lg = linear_model.LogisticRegression(random_state=42,solver='lbfgs', multi_class='ovr')

model = lg.fit(X_train_scaled,y_train)


X_test_scaled = scaler.transform(X_test)

y_pred_s = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred_s)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 75.56%
